/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    get: operations["HealthController_check"];
  };
  "/v1/districts": {
    get: operations["DistrictsController_findAll"];
  };
  "/v1/districts/nearest": {
    get: operations["DistrictsController_findNearest"];
  };
  "/v1/venues/map": {
    get: operations["VenuesController_mapView"];
  };
  "/v1/venues": {
    get: operations["VenuesController_list"];
  };
  "/v1/venues/{slug}": {
    get: operations["VenuesController_detail"];
  };
  "/v1/me/lists": {
    get: operations["FavoritesController_list"];
    post: operations["FavoritesController_create"];
  };
  "/v1/me/lists/{id}/venues": {
    post: operations["FavoritesController_addVenue"];
  };
  "/v1/venues/{id}/report": {
    post: operations["ReportsController_submit"];
  };
  "/v1/admin/queue": {
    get: operations["AdminQueueController_list"];
  };
  "/v1/admin/queue/{id}/approve": {
    post: operations["AdminQueueController_approve"];
  };
  "/v1/admin/queue/{id}/reject": {
    post: operations["AdminQueueController_reject"];
  };
  "/v1/admin/venues": {
    post: operations["AdminVenuesController_create"];
  };
  "/v1/admin/venues/{id}": {
    put: operations["AdminVenuesController_update"];
  };
  "/v1/admin/venues/{id}/revert/{versionId}": {
    post: operations["AdminVenuesController_revert"];
  };
  "/v1/admin/import": {
    post: operations["AdminVenuesController_importCsv"];
  };
  "/v1/admin/reports/data-quality": {
    get: operations["AdminReportsController_dataQuality"];
  };
  "/v1/admin/export": {
    get: operations["AdminExportController_export"];
  };
  "/v1/admin/users/{id}/roles": {
    put: operations["AdminUsersController_assignRole"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  HealthController_check: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DistrictsController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  DistrictsController_findNearest: {
    parameters: {
      query: {
        lat: string;
        lng: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  VenuesController_mapView: {
    parameters: {
      query: {
        bbox: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  VenuesController_list: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  VenuesController_detail: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  FavoritesController_list: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  FavoritesController_create: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  FavoritesController_addVenue: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ReportsController_submit: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminQueueController_list: {
    parameters: {
      query: {
        type: string;
        status: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminQueueController_approve: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminQueueController_reject: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminVenuesController_create: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminVenuesController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminVenuesController_revert: {
    parameters: {
      path: {
        id: string;
        versionId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminVenuesController_importCsv: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminReportsController_dataQuality: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminExportController_export: {
    parameters: {
      query: {
        format: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminUsersController_assignRole: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
}
